import "reflect-metadata";
import { DataSource } from "typeorm";
import {
  Order,
  Product,
  Vehicle,
  Notification,
  Warehouse,
  ProductLocation,
  ProductBatch,
  LogisticBatch,
  Route,
  RoutePoint,
  Invoice,
  InvoiceItem,
  Contract,
  ContractItem,
  User,
  Role,
  Permission,
  UserActivity,
  PickingList,
  PickingListItem,
  Inventory,
  InventoryItem,
  Return,
  ReturnItem,
  IotSensor,
  SensorReading,
  GpsTracker,
  RfidSystem,
  TemperatureSensor,
  KpiMetric
} from "./entities";

export const AppDataSource = new DataSource({
  type: "postgres",
  host: "localhost",
  port: 5432,
  username: "postgres",
  password: "admin",
  database: "postgres",
  synchronize: true,
  logging: false,
  entities: [
    Order,
    Product,
    Vehicle,
    Notification,
    Warehouse,
    ProductLocation,
    ProductBatch,
    LogisticBatch,
    Route,
    RoutePoint,
    Invoice,
    InvoiceItem,
    Contract,
    ContractItem,
    User,
    Role,
    Permission,
    UserActivity,
    PickingList,
    PickingListItem,
    Inventory,
    InventoryItem,
    Return,
    ReturnItem,
    IotSensor,
    SensorReading,
    GpsTracker,
    RfidSystem,
    TemperatureSensor,
    KpiMetric
  ],
  migrations: [],
  subscribers: [],
});